### ISSUE TITLE
why do we need +1

### ISSUE THREAD

**Issue by jjhesk** [robriks/ethernaut-solutions#1]
https://github.com/robriks/ethernaut-solutions/blob/ae12b0f7e728047f59b9816440d4f7f9a8a0af12/alien-codex/Solution.sol#L20

why do we need to offset this with + 1 at the end?

**Comment by robriks** [comment]
> https://github.com/robriks/ethernaut-solutions/blob/ae12b0f7e728047f59b9816440d4f7f9a8a0af12/alien-codex/Solution.sol#L20
> 
> why do we need to offset this with + 1 at the end?

The + 1 is necessary to 'overflow' into the zero slot. 

Imagine we add `arraySlot` to both sides of the equation in that line. Now the left side is `type(uint256).max` so if you want to 'overflow' that value to 0 you need push it over the max by incrementing by one
