### ISSUE TITLE
fun test

### ISSUE THREAD

**Issue by jjhesk** [robriks/ethernaut-solutions#2]
https://github.com/robriks/ethernaut-solutions/blob/ae12b0f7e728047f59b9816440d4f7f9a8a0af12/delegation/Solution.sol#L41C60-L41C60

Test in both v0.6 and v0.8
there should be `delegatecall` to start from the attacker contract since that will be using the context in the attacker and there is not slot memory for this contract. We are intended to changing the Delegation contract owner so instead of this we should call `call` to trigger the inside the contract as the identity of Delegation that use the logic in Delegate.

**Comment by robriks** [comment]
Thanks. e5f49f6
